# Generated by Django 5.1.3 on 2024-11-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
