# Generated by Django 5.1.3 on 2024-11-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0006_alter_post_options_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-username"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
