# Generated by Django 5.1.3 on 2024-11-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0007_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username", "age"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
